/**
 * Converters for JSON to CSV, YAML, TypeScript, Go Struct, etc.
 */

// Flatten nested object for CSV conversion
export function flattenObject(obj: any, prefix = ''): Record<string, any> {
  return Object.keys(obj).reduce((acc: Record<string, any>, k: string) => {
    const pre = prefix.length ? prefix + '.' : '';
    if (typeof obj[k] === 'object' && obj[k] !== null && !Array.isArray(obj[k])) {
      Object.assign(acc, flattenObject(obj[k], pre + k));
    } else if (Array.isArray(obj[k])) {
      acc[pre + k] = JSON.stringify(obj[k]);
    } else {
      acc[pre + k] = obj[k];
    }
    return acc;
  }, {});
}

// Convert JSON array/object to CSV
export function jsonToCsv(jsonInput: string): string {
  const parsed = typeof jsonInput === 'string' ? JSON.parse(jsonInput) : jsonInput;
  const arrayData = Array.isArray(parsed) ? parsed : [parsed];
  
  if (arrayData.length === 0) return '';
  
  const flattenedData = arrayData.map(item => typeof item === 'object' && item !== null ? flattenObject(item) : { value: item });
  const headers = Array.from(new Set(flattenedData.flatMap(item => Object.keys(item))));
  
  const csvRows = [
    headers.join(','),
    ...flattenedData.map(row => 
      headers.map(header => {
        const val = row[header];
        if (val === undefined || val === null) return '""';
        const str = String(val).replace(/"/g, '""');
        return `"${str}"`;
      }).join(',')
    )
  ];
  
  return csvRows.join('\n');
}

// Convert JSON to clean TypeScript Interface/Type definitions
export function jsonToTypescript(jsonInput: string, rootName = 'RootObject'): string {
  const parsed = typeof jsonInput === 'string' ? JSON.parse(jsonInput) : jsonInput;
  
  function getType(val: any, name: string, interfaces: string[]): string {
    if (val === null) return 'any';
    if (Array.isArray(val)) {
      if (val.length === 0) return 'any[]';
      const itemType = getType(val[0], name + 'Item', interfaces);
      return `${itemType}[]`;
    }
    if (typeof val === 'object') {
      const interfaceName = name.charAt(0).toUpperCase() + name.slice(1);
      const props = Object.keys(val).map(key => {
        const propType = getType(val[key], key, interfaces);
        const isCleanKey = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key);
        const formattedKey = isCleanKey ? key : `"${key}"`;
        return `  ${formattedKey}: ${propType};`;
      });
      
      const interfaceStr = `export interface ${interfaceName} {\n${props.join('\n')}\n}`;
      interfaces.push(interfaceStr);
      return interfaceName;
    }
    return typeof val;
  }
  
  const interfaces: string[] = [];
  getType(parsed, rootName, interfaces);
  return Array.from(new Set(interfaces.reverse())).join('\n\n');
}

// Convert JSON to Go Struct
export function jsonToGo(jsonInput: string, rootName = 'AutoGenerated'): string {
  const parsed = typeof jsonInput === 'string' ? JSON.parse(jsonInput) : jsonInput;
  
  function toCamelCase(str: string): string {
    return str.replace(/[^a-zA-Z0-9]+(.)/g, (_, chr) => chr.toUpperCase())
              .replace(/^[a-z]/, char => char.toUpperCase());
  }

  function getGoType(val: any, name: string, structs: string[]): string {
    if (val === null) return 'interface{}';
    if (typeof val === 'boolean') return 'bool';
    if (typeof val === 'number') return Number.isInteger(val) ? 'int' : 'float64';
    if (typeof val === 'string') return 'string';
    if (Array.isArray(val)) {
      if (val.length === 0) return '[]interface{}';
      const itemType = getGoType(val[0], name, structs);
      return `[]${itemType}`;
    }
    if (typeof val === 'object') {
      const structName = toCamelCase(name);
      const fields = Object.keys(val).map(key => {
        const fieldName = toCamelCase(key);
        const fieldType = getGoType(val[key], key, structs);
        return `\t${fieldName} ${fieldType} \`json:"${key}"\``;
      });
      const structStr = `type ${structName} struct {\n${fields.join('\n')}\n}`;
      structs.push(structStr);
      return structName;
    }
    return 'interface{}';
  }

  const structs: string[] = [];
  getGoType(parsed, rootName, structs);
  return Array.from(new Set(structs.reverse())).join('\n\n');
}

// Simple YAML Serializer
export function jsonToYaml(jsonInput: string): string {
  const parsed = typeof jsonInput === 'string' ? JSON.parse(jsonInput) : jsonInput;
  
  function stringifyYaml(obj: any, indent = 0): string {
    const spaces = ' '.repeat(indent);
    if (obj === null || obj === undefined) return 'null\n';
    if (typeof obj === 'boolean' || typeof obj === 'number') return `${obj}\n`;
    if (typeof obj === 'string') return `"${obj.replace(/"/g, '\\"')}"\n`;
    
    if (Array.isArray(obj)) {
      if (obj.length === 0) return '[]\n';
      return obj.map(item => {
        if (typeof item === 'object' && item !== null) {
          const itemStr = stringifyYaml(item, indent + 2).trimStart();
          return `${spaces}- ${itemStr}`;
        }
        return `${spaces}- ${stringifyYaml(item, 0)}`;
      }).join('');
    }
    
    if (typeof obj === 'object') {
      const keys = Object.keys(obj);
      if (keys.length === 0) return '{}\n';
      return keys.map(key => {
        const val = obj[key];
        if (typeof val === 'object' && val !== null) {
          return `${spaces}${key}:\n${stringifyYaml(val, indent + 2)}`;
        }
        return `${spaces}${key}: ${stringifyYaml(val, 0)}`;
      }).join('');
    }
    
    return `${obj}\n`;
  }
  
  return stringifyYaml(parsed);
}
