import { useState } from 'react';
import { jsonToGo } from '../../utils/json-converters';
import { Copy, Check, Code } from 'lucide-react';

const SAMPLE_PAYLOAD = `{
  "server_id": 401,
  "hostname": "edge-us-east-1",
  "enabled": true,
  "max_connections": 1000
}`;

export default function JsonToGo() {
  const [input, setInput] = useState(SAMPLE_PAYLOAD);
  const [structName, setStructName] = useState('ServerConfig');
  const [goOutput, setGoOutput] = useState(() => jsonToGo(SAMPLE_PAYLOAD, 'ServerConfig'));
  const [copied, setCopied] = useState(false);

  const handleConvert = () => {
    try {
      setGoOutput(jsonToGo(input, structName || 'AutoGenerated'));
    } catch (e) {
      setGoOutput('// Error: Invalid JSON input');
    }
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(goOutput);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div style={{ background: 'var(--bg-card)', border: '1px solid var(--border-subtle)', borderRadius: '0.75rem', padding: '1.25rem' }}>
      <div style={{ marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '1rem' }}>
        <label style={{ fontSize: '0.85rem', fontWeight: 700, color: 'var(--text-secondary)' }}>Go Struct Name:</label>
        <input
          type="text"
          value={structName}
          onChange={(e) => setStructName(e.target.value)}
          style={{ background: 'var(--bg-primary)', color: 'var(--text-primary)', border: '1px solid var(--border-highlight)', padding: '0.35rem 0.75rem', borderRadius: '0.375rem', fontFamily: 'var(--font-mono)', fontSize: '0.85rem' }}
        />
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '1rem', marginBottom: '1rem' }}>
        <div>
          <label style={{ fontSize: '0.85rem', fontWeight: 700, color: 'var(--text-secondary)', display: 'block', marginBottom: '0.5rem' }}>JSON Sample Input</label>
          <textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            style={{ width: '100%', height: '260px', background: 'var(--bg-primary)', color: 'var(--text-primary)', fontFamily: 'var(--font-mono)', fontSize: '0.85rem', padding: '0.75rem', border: '1px solid var(--border-subtle)', borderRadius: '0.375rem', outline: 'none' }}
          />
        </div>

        <div>
          <label style={{ fontSize: '0.85rem', fontWeight: 700, color: 'var(--text-secondary)', display: 'block', marginBottom: '0.5rem' }}>Go Struct Definition Output</label>
          <textarea
            value={goOutput}
            readOnly
            style={{ width: '100%', height: '260px', background: 'var(--bg-primary)', color: 'var(--accent-cyan)', fontFamily: 'var(--font-mono)', fontSize: '0.85rem', padding: '0.75rem', border: '1px solid var(--border-subtle)', borderRadius: '0.375rem', outline: 'none' }}
          />
        </div>
      </div>

      <div style={{ display: 'flex', gap: '0.75rem' }}>
        <button
          onClick={handleConvert}
          style={{ background: 'var(--accent-emerald)', color: '#000', border: 'none', padding: '0.5rem 1.25rem', borderRadius: '0.375rem', fontWeight: 700, fontSize: '0.85rem', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '0.4rem' }}
        >
          <Code size={16} /> Generate Go Struct
        </button>

        <button
          onClick={handleCopy}
          style={{ background: 'var(--bg-card-hover)', color: 'var(--text-primary)', border: '1px solid var(--border-highlight)', padding: '0.5rem 1rem', borderRadius: '0.375rem', fontSize: '0.85rem', fontWeight: 600, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '0.4rem' }}
        >
          {copied ? <Check size={16} color="var(--accent-emerald)" /> : <Copy size={16} />}
          {copied ? 'Copied Struct' : 'Copy Go Struct'}
        </button>
      </div>
    </div>
  );
}
